Removed duplicate entries caused by ascertainment of data in one of the modules (Prescription Medications)

In [10]:
# Dependencies
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st
from scipy.stats import linregress
import pyreadstat
import xport

In [11]:
# Data_update import 
Dataset_update = pd.read_csv("Datasets/Dataset_update")

# Display dataframe
Dataset_update

,Respondent ID,Number of Rx Meds,Gender,Age at Screening,Race,Educational Attainment,Family Income to Poverty Ratio,Minutes of Vigorous Work Daily,Minutes of Moderate Work Daily,Minutes of Vigorous Recreation Daily,Minutes of Moderate Recreation Daily,Minutes of Sedentary Activity Daily,Sleep Hours Week/Workdays,Sleep Hours Weekends,Told Doctor About Sleep Issues,Feeling Tired During Day Frequency
0,109263.0,NaN,1.0,2.0,6.0,NaN,4.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,109264.0,NaN,2.0,13.0,1.0,NaN,0.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,109265.0,NaN,1.0,2.0,3.0,NaN,3.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,109266.0,NaN,2.0,29.0,6.0,5.0,5.00,NaN,NaN,60.0,30.0,480.0,7.5,8.0,2.0,5.397605e-79
4,109267.0,1.0,2.0,21.0,2.0,4.0,5.00,NaN,NaN,90.0,NaN,540.0,8.0,8.0,2.0,2.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32957,124821.0,4.0,1.0,63.0,4.0,2.0,3.71,10.0,NaN,NaN,NaN,60.0,8.0,9.0,2.0,2.000000e+00
32958,124821.0,4.0,1.0,63.0,4.0,2.0,3.71,10.0,NaN,NaN,NaN,60.0,8.0,9.0,2.0,2.000000e+00
32959,124821.0,4.0,1.0,63.0,4.0,2.0,3.71,10.0,NaN,NaN,NaN,60.0,8.0,9.0,2.0,2.000000e+00
32960,124822.0,2.0,1.0,74.0,2.0,3.0,NaN,NaN,180.0,45.0,60.0,240.0,5.5,8.0,2.0,4.000000e+00
32961,124822.0,2.0,1.0,74.0,2.0,3.0,NaN,NaN,180.0,45.0,60.0,240.0,5.5,8.0,2.0,4.000000e+00

See "Data_Check" for the analysis performed to check that the data imported correctly. During this analysis, we discovered that SEQN (Respondent ID) cannot be used as a unique identifier for the Prescription Meds dataset because a single respondent may take multiple medications, resulting in multiple rows per respondent (see Respondent ID 124821.0 for example). Because the specific data point we want to analyze with regards to Prescription Meds will remain consistent across multiple entries per respondent, removing duplicate Responent IDs seemed to be the most straightforward approach.

In [12]:
#Based on above analysis description, removed duplicates within the Respondent ID column
Dataset_update_remove_dups = Dataset_update.drop_duplicates(subset=['Respondent ID'], keep='last')
Dataset_update_remove_dups

,Respondent ID,Number of Rx Meds,Gender,Age at Screening,Race,Educational Attainment,Family Income to Poverty Ratio,Minutes of Vigorous Work Daily,Minutes of Moderate Work Daily,Minutes of Vigorous Recreation Daily,Minutes of Moderate Recreation Daily,Minutes of Sedentary Activity Daily,Sleep Hours Week/Workdays,Sleep Hours Weekends,Told Doctor About Sleep Issues,Feeling Tired During Day Frequency
0,109263.0,NaN,1.0,2.0,6.0,NaN,4.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,109264.0,NaN,2.0,13.0,1.0,NaN,0.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,109265.0,NaN,1.0,2.0,3.0,NaN,3.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,109266.0,NaN,2.0,29.0,6.0,5.0,5.00,NaN,NaN,60.0,30.0,480.0,7.5,8.0,2.0,5.397605e-79
4,109267.0,1.0,2.0,21.0,2.0,4.0,5.00,NaN,NaN,90.0,NaN,540.0,8.0,8.0,2.0,2.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32953,124818.0,NaN,1.0,40.0,4.0,5.0,3.82,NaN,NaN,NaN,NaN,420.0,6.0,7.0,2.0,2.000000e+00
32954,124819.0,NaN,1.0,2.0,4.0,NaN,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32955,124820.0,NaN,2.0,7.0,3.0,NaN,1.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32959,124821.0,4.0,1.0,63.0,4.0,2.0,3.71,10.0,NaN,NaN,NaN,60.0,8.0,9.0,2.0,2.000000e+00
32961,124822.0,2.0,1.0,74.0,2.0,3.0,NaN,NaN,180.0,45.0,60.0,240.0,5.5,8.0,2.0,4.000000e+00

In [13]:
#checked the counts of each column against published data counts on CDC website
Dataset_update_remove_dups.count()

Respondent ID                           15560
Number of Rx Meds                        6844
Gender                                  15560
Age at Screening                        15560
Race                                    15560
Educational Attainment                   9232
Family Income to Poverty Ratio          13359
Minutes of Vigorous Work Daily           2402
Minutes of Moderate Work Daily           4164
Minutes of Vigorous Recreation Daily     2417
Minutes of Moderate Recreation Daily     3893
Minutes of Sedentary Activity Daily      9676
Sleep Hours Week/Workdays               10105
Sleep Hours Weekends                    10099
Told Doctor About Sleep Issues          10195
Feeling Tired During Day Frequency      10195
dtype: int64

After removing duplicates, the counts per column match what is published on the CDC website with the exception of "Number of Rx Meds" which is expected given the multiple entries per respondent issue.

In [14]:
#wrote new data set to csv
Dataset_update_remove_dups.to_csv("Datasets/Dataset_update_remove_dups",
                  encoding="utf-8", index=False, header=True)